//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenAPI.Validator.Properties
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenAPI.Validator.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top level properties should be one of name, type, id, location, properties, tags, plan, sku, etag, managedBy, identity, zones. Model definition &apos;{0}&apos; has extra properties [&apos;{1}&apos;]..
        /// </summary>
        internal static string AllowedTopLevelProperties
        {
            get
            {
                return ResourceManager.GetString("AllowedTopLevelProperties", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to API Version must be in the format: yyyy-MM-dd, optionally followed by -preview, -alpha, -beta, -rc, -privatepreview..
        /// </summary>
        internal static string APIVersionFormatIsNotValid
        {
            get
            {
                return ResourceManager.GetString("APIVersionFormatIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top level property names should not be repeated inside the properties bag for ARM resource &apos;{0}&apos;. Properties [{1}] conflict with ARM top level properties. Please rename these..
        /// </summary>
        internal static string ArmPropertiesBagValidationMessage
        {
            get
            {
                return ResourceManager.GetString("ArmPropertiesBagValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property named: &apos;{0}&apos;, must follow camelCase style. Example: &apos;{1}&apos;..
        /// </summary>
        internal static string BodyPropertyNameCamelCase
        {
            get
            {
                return ResourceManager.GetString("BodyPropertyNameCamelCase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Booleans are not descriptive and make them hard to use. Consider using string enums with allowed set of values defined. Property: {0}.
        /// </summary>
        internal static string BooleanPropertyNotRecommended
        {
            get
            {
                return ResourceManager.GetString("BooleanPropertyNotRecommended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found a type set &apos;{0}&apos; which is circularly defined..
        /// </summary>
        internal static string CircularBaseSchemaSet
        {
            get
            {
                return ResourceManager.GetString("CircularBaseSchemaSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Circular reference detected: {0}.
        /// </summary>
        internal static string CircularReference
        {
            get
            {
                return ResourceManager.GetString("CircularReference", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collection object &apos;{0}&apos; returned by list operation &apos;{1}&apos; with &apos;x-ms-pageable&apos; extension, has no property named &apos;value&apos;..
        /// </summary>
        internal static string CollectionObjectPropertiesNamingMessage
        {
            get
            {
                return ResourceManager.GetString("CollectionObjectPropertiesNamingMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference specifies the definition {0} that does not exist..
        /// </summary>
        internal static string DefinitionDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("DefinitionDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property named: &apos;{0}&apos;, for definition: &apos;{1}&apos; must follow camelCase style. Example: &apos;{2}&apos;..
        /// </summary>
        internal static string DefinitionsPropertiesNameCamelCase
        {
            get
            {
                return ResourceManager.GetString("DefinitionsPropertiesNameCamelCase", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;Delete&apos; operation &apos;{0}&apos; must not have a request body..
        /// </summary>
        internal static string DeleteMustNotHaveRequestBody
        {
            get
            {
                return ResourceManager.GetString("DeleteMustNotHaveRequestBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found operation objects with duplicate operationId &apos;{0}&apos;. OperationId must be unique among all operations described in the API..
        /// </summary>
        internal static string DuplicateOperationIdException
        {
            get
            {
                return ResourceManager.GetString("DuplicateOperationIdException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty x-ms-client-name property..
        /// </summary>
        internal static string EmptyClientName
        {
            get
            {
                return ResourceManager.GetString("EmptyClientName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error parsing swagger file.
        /// </summary>
        internal static string ErrorParsingSpec
        {
            get
            {
                return ResourceManager.GetString("ErrorParsingSpec", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reached Maximum reference depth when resolving reference &apos;{0}&apos;..
        /// </summary>
        internal static string ExceededMaximumReferenceDepth
        {
            get
            {
                return ResourceManager.GetString("ExceededMaximumReferenceDepth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generating client model from swagger model..
        /// </summary>
        internal static string GeneratingClient
        {
            get
            {
                return ResourceManager.GetString("GeneratingClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Guid used in model definition &apos;{1}&apos; for property &apos;{0}&apos;. Usage of Guid is not recommanded. If GUIDs are absolutely required in your service, please get sign off from the Azure API review board..
        /// </summary>
        internal static string GuidUsageNotRecommended
        {
            get
            {
                return ResourceManager.GetString("GuidUsageNotRecommended", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permissible values for HTTP Verb are delete,get,put,patch,head,options,post. .
        /// </summary>
        internal static string HttpVerbIsNotValid
        {
            get
            {
                return ResourceManager.GetString("HttpVerbIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found incompatible property types {1}, {2} for property &apos;{0}&apos; in schema inheritance chain {3}.
        /// </summary>
        internal static string IncompatibleTypesInBaseSchema
        {
            get
            {
                return ResourceManager.GetString("IncompatibleTypesInBaseSchema", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Found incompatible property types {1}, {2} for property &apos;{0}&apos; in schema {3}.
        /// </summary>
        internal static string IncompatibleTypesInSchemaComposition
        {
            get
            {
                return ResourceManager.GetString("IncompatibleTypesInSchemaComposition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swagger specification is missing info section.
        /// </summary>
        internal static string InfoSectionMissing
        {
            get
            {
                return ResourceManager.GetString("InfoSectionMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Input parameter is required..
        /// </summary>
        internal static string InputRequired
        {
            get
            {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The schema&apos;s &apos;{0}&apos; ancestors should have at lease one property.
        /// </summary>
        internal static string InvalidAncestors
        {
            get
            {
                return ResourceManager.GetString("InvalidAncestors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collection format &apos;{0}&apos; is not a valid collection format (in parameter &apos;{1}&apos;)..
        /// </summary>
        internal static string InvalidCollectionFormat
        {
            get
            {
                return ResourceManager.GetString("InvalidCollectionFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot use &apos;extend&apos; property with &apos;allOf&apos; property in schema {0}.
        /// </summary>
        internal static string InvalidTypeExtendsWithAllOf
        {
            get
            {
                return ResourceManager.GetString("InvalidTypeExtendsWithAllOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not implemented in SwaggerSchema.ToType extension method..
        /// </summary>
        internal static string InvalidTypeInSwaggerSchema
        {
            get
            {
                return ResourceManager.GetString("InvalidTypeInSwaggerSchema", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Successfully initialized modeler {0} v {1}..
        /// </summary>
        internal static string ModelerInitialized
        {
            get
            {
                return ResourceManager.GetString("ModelerInitialized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collection format &quot;multi&quot; is only supported for Query parameters (parameter &apos;{0}&apos;)..
        /// </summary>
        internal static string MultiCollectionFormatNotSupported
        {
            get
            {
                return ResourceManager.GetString("MultiCollectionFormatNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only &apos;application/json&apos; content-type is supported by ARM..
        /// </summary>
        internal static string NonAppJsonTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString("NonAppJsonTypeNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; does not declare any MIME type for the return body. Generated code will not deserialize the content..
        /// </summary>
        internal static string NoProduceOperationWithBody
        {
            get
            {
                return ResourceManager.GetString("NoProduceOperationWithBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OperationId is required for all operations. Please add it for &apos;{0}&apos; operation of &apos;{1}&apos; path..
        /// </summary>
        internal static string OperationIdMissing
        {
            get
            {
                return ResourceManager.GetString("OperationIdMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operations API must be implemented for &apos;{0}&apos;..
        /// </summary>
        internal static string OperationsAPINotImplemented
        {
            get
            {
                return ResourceManager.GetString("OperationsAPINotImplemented", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Options HTTP verb is not supported..
        /// </summary>
        internal static string OptionsNotSupported
        {
            get
            {
                return ResourceManager.GetString("OptionsNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parsing swagger json file..
        /// </summary>
        internal static string ParsingSwagger
        {
            get
            {
                return ResourceManager.GetString("ParsingSwagger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} has different responses for PUT/GET/PATCH operations. The PUT/GET/PATCH operations must have same schema response..
        /// </summary>
        internal static string PutGetPatchResponseInvalid
        {
            get
            {
                return ResourceManager.GetString("PutGetPatchResponseInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The 200 response model for an ARM PUT operation must have x-ms-azure-resource extension set to true in its hierarchy. Operation: &apos;{0}&apos; Model: &apos;{1}&apos;..
        /// </summary>
        internal static string PutOperationResourceResponseValidationMessage
        {
            get
            {
                return ResourceManager.GetString("PutOperationResourceResponseValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; in Model &apos;{1}&apos; is marked readOnly and is also required. This is not allowed..
        /// </summary>
        internal static string ReadOnlyNotRequired
        {
            get
            {
                return ResourceManager.GetString("ReadOnlyNotRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference path &apos;{0}&apos; does not exist in the definition section of the Swagger document..
        /// </summary>
        internal static string ReferenceDoesNotExist
        {
            get
            {
                return ResourceManager.GetString("ReferenceDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model definition &apos;{0}&apos; must have the properties &apos;name&apos;, &apos;id&apos; and &apos;type&apos; in its hierarchy and these properties must be marked as readonly..
        /// </summary>
        internal static string ResourceModelIsNotValid
        {
            get
            {
                return ResourceManager.GetString("ResourceModelIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sku Model definition &apos;{0}&apos; is not valid. A Sku model must have &apos;name&apos; property. It can also have &apos;tier&apos;, &apos;size&apos;, &apos;family&apos;, &apos;capacity&apos; as optional properties..
        /// </summary>
        internal static string SkuModelIsNotValid
        {
            get
            {
                return ResourceManager.GetString("SkuModelIsNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swagger specification is missing title in info section.
        /// </summary>
        internal static string TitleMissing
        {
            get
            {
                return ResourceManager.GetString("TitleMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tracked resource &apos;{0}&apos; must have a get operation..
        /// </summary>
        internal static string TrackedResourceGetOperationMissing
        {
            get
            {
                return ResourceManager.GetString("TrackedResourceGetOperationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The child tracked resource, &apos;{0}&apos; with immediate parent &apos;{1}&apos;, must have a list by immediate parent operation..
        /// </summary>
        internal static string TrackedResourceListByImmediateParentOperationMissing
        {
            get
            {
                return ResourceManager.GetString("TrackedResourceListByImmediateParentOperationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The tracked resource, &apos;{0}&apos;, must have a list by resource group operation.(This rule does not apply for tenant level resources.).
        /// </summary>
        internal static string TrackedResourceListByResourceGroupOperationMissing
        {
            get
            {
                return ResourceManager.GetString("TrackedResourceListByResourceGroupOperationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The tracked resource, &apos;{0}&apos;, must have a list by subscriptions operation..
        /// </summary>
        internal static string TrackedResourceListBySubscriptionsOperationMissing
        {
            get
            {
                return ResourceManager.GetString("TrackedResourceListBySubscriptionsOperationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tracked resource &apos;{0}&apos; must have patch operation that at least supports the update of tags. It&apos;s strongly recommended that the PATCH operation supports update of all mutable properties as well..
        /// </summary>
        internal static string TrackedResourcePatchOperationMissing
        {
            get
            {
                return ResourceManager.GetString("TrackedResourcePatchOperationMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple resource providers are not allowed in a single spec. More than one the resource paths were found: &apos;{0}&apos;..
        /// </summary>
        internal static string UniqueResourcePaths
        {
            get
            {
                return ResourceManager.GetString("UniqueResourcePaths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid swagger 2.0 specification. Missing version property. .
        /// </summary>
        internal static string UnknownSwaggerVersion
        {
            get
            {
                return ResourceManager.GetString("UnknownSwaggerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; has a response body in response &apos;{1}&apos;, but did not have a supported MIME type (&apos;application/json&apos; or &apos;application/octet-stream&apos;) in its Produces property..
        /// </summary>
        internal static string UnsupportedMimeTypeForResponseBody
        {
            get
            {
                return ResourceManager.GetString("UnsupportedMimeTypeForResponseBody", resourceCulture);
            }
        }
    }
}
